language: java

sudo: false

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean test jacocoTestReport war"

after_success:
- bash <(curl -s https://codecov.io/bash)
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- scp build/libs/ROOT.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: uiMRS/iyHjLLL1HdbuH7coKTjVtoDEnRCVs5Ep1c6fnTbxAhWRGMJfWrGkqDg/Q62MYr9Yn/biPFi+3+wTrxm+f8992ncE6p1jO7Wv6gQ5HhC3ahdSsNOcFBb0QiPgM7VWpUS9cJvag7x7gcnhmc8O9g3zxnIMq7ahEGT5jm9wUUcUlkw2QxUU5Ily6E5Sx0miUiUriatNj1ZP6bdBuJmMw2IfP5Bob3QuHIbSRNRHzAcaa0PDBR8mtzuHjqH+DcctBS4w9BwK+j+m+xgViCf9Pp5Xnd/o+e7/vYDE2blVnklVRZ3oZerW33aFt3srfpjeKuBcGr+ctmyGqVV8F60MVSbV8cAhalM1CEO+1ml6J1vwc0ede5P33qJILYMyW95rl/ss/L03XHJZ6eCHZbJyET3o+ecthDPs/ccc00qFW8O/jjrhHyjjUGEtFNUzQxdl1Vt4WlaPQqbUVeaujAI2CPPArETz7E0oo7DZyKGsTLm7YUyC4xKCI9k3aQrCsAFWu6idnkqyAtrSdrE0kCFnfbahoorjfQYy2qCa2wm/RjwiORMSDqnws7ko8YBy359SXdkHs2CYxyR1NssOcZ5+l0lzV7Xxizpq33/VW4EXSy7LRhHIxXYCHsSAhlcvu5tfOZoegdHwod3TE+cg8Ty5mKg25FDTLoge7BkZhI8xw=
  - secure: O3QyQK1aqMWeJDjwJs7wE5g2Inxseiw+PKkeF0BjCaaW7GAT10gcU+jPRjchmIMxkXD5+XUYEiz7rwFPqmhc/PnolH7oy6WCnGif0rcjIXpwtRClaPkOuVwkPbzmi0/p67hzp+zrpZMiyGeWZx8amgwjJ9odS03cSZB80O77copeGqGoDXY/1eRglgenXib54Vmz+nMriYzZnKlJeWIlImeo1s2VHId27UdmgtmWEU45/cgycRIsQ174swD8QBZXps9f6XvOKECmYsVq/nAkhNJZNZpnUHvshDhyicrfWNz+5hsKKPcefzKir97EPifrwaJbZwM6nfBL+EDXSPVSTikisWKJ/Ae3eP2SvsnBQqlAlxPeA8CT/CwMrrS4DAklxpun+91/+IgDxqUGsoU6EM1yv2s13KtjdZ328dvmm52lcRaALWeqld2WmW6CTiMkoe/9fuEAZk3TVDUT412i5DTBRfNxPsVoMtCnN2OSfHz4OAbQtDLOfNp/QkhjzDbaBaPp67VesSg9U62QGJUxYvNSHUIFXut1F3kq2VIxhaIbMwXjWPEgcPRVoKaBx+WIITmyKcI8gsqY1J9QJcYq25Vh7Bj4FgLGzV7FQpIAZ234iMXQ+6TQH39LJ7PpoMGMu53FuQ1AG4WtQFSiLkJQa7+I/lES5dj9wcABKRLSohs=
  - secure: nObHTHEdanNHRXQOjlhy/o2JIkxYJFTrBXu/fBIlbiM64axG4s+AGL57eKYAZ7TWhOmK5zCKyxmSBru8s1tdN9blQKxBO130G8TTdJxb4kOl+MUj8Uw8MxSSS884kd4PVOfkJHogKl3y959Xj5vjDhNj6qxaXk831SwDTdAlJrZ3G9m92pDeuAqZltl73fmc4hIoMszXDBuki40XKm7MFzjnwxsS+Pxp/6YVxATZr94Jq8BVNJzczYvPBcnYcDxtbGKQF6e/3Z5gpz7LsZaPnRjB18hwZNID3z6E5UCI885yv89aNufwVbkglWbUfLlnADBXAryq7w0/lO+I373gFLZgKm5Uo9UR3vUZaekrK9nSOLjLw7VNT8GoEUZhn4NRBOixpeAVcHeQgsL6cyi6bgLP0I5tcjb2Y/745NGVxH/wOKxe53NVtBn4jx55z0pArcxa/J0xxRUTYXM3hwSe5yRUmcmiJshouTR8CNFt89mrJx9sfgdnbOjJpTAOQ9LFOpxMSd3T0JZD/Ccq81v20pjNv3lgf+XlXRVh6XZjNgVmsTz8mMe+AcQUJ9LkBt+6hvuiUmhGdYVz8LyECiwc9AqZxFgpfeW1eW9sudVwSqP+nqYPUxJBZu54swu2gUbX4Jzc0xHeeTnWySyuOUyR9QklqWsbHtbQnp2VMGv0rJ0=