language: java

sudo: required

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean test jacocoTestReport war"

after_success:
- bash <(curl -s https://codecov.io/bash)
- sudo apt-get -y install sshpass
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- sshpass scp -i ~/.ssh/id_rsa build/libs/ROOT.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: rqeNHHh/CSY/rA62DwyFiVHaMz/VnqX2zhPzMYopX6GxLBfr9nfBkcIuAwv70mtAtirsi3n+g57DjmA/vyEFv5MV24PCxSjdW/qP9qu9M8XZ/+ohFeTMnkq8hb5EGyg74b3VpM4KzZhGqcuVWZLPAK3lfW/x7hrsoIWdbtF8pThXdGmvieuGXhXRmKQCdNA4gGhiG2NwQRAWC4t/KB4GZP1yed90cr6J9v7qUGKncV36nraO4Mddf7DxFH/6SkdMURpEpLYtEWuJZc6utHhtizSp1Z3to34S6w6OwyuVNJz8eQZtIzidjzqQW9EFrjT4qrsCTlthAHdkrXp/8tkiqrxHD1qtPP5dwWIpkmHA8IFhVRMY1hk0lAm4n9A83RzNsIc7NPAUzbBXYskgw8W0pjecLaHsI4r5QU879u4JkApsfsuILERJ0d2MGA1I9dKlBRlF99WQ1fjJBinHNwlz/xUK3gYenp4Jt88m6WtbtJgyHESMp6WoXmcvA6sj3U1etMhuczkd14ASljnv8wh/mhBpSrXYN08uG/9NmA6trnT1bFfUIIpPjbrBQDpHCMfnL8mu2syuYOw4kKyEcj2kkEcGIMWQIgpetQ61H0Dz92bEVaHI9fSRHeNzV/dHT0369aatPZlqqtyMZFJFgT+NskCJXPmuDFuHJA7rLvvX7WU=
  - secure: J7Xz/k3t47aS+m/5fzmvkgXduLubEKGR7WgqvvabuNs/Qrb7vXww/gEx08fQRxjxY2UqHy59k7ze4hpZ3yKDdL7cZrrSlZp1/Y5MepCrqajWEC+YX20JH2c8KRYjBicq8cywDSViAaSLW3PtuXPhHM8+WbXsJ85OdtADnbvuFSv91kPZh6AT1Cv9LG8rtqHS491BpudWne9koth/+XBLBBuGP4MrzxMrHlXS49OTaxUcOea8TKhMzJkFBfAc5xHEHoV1mOUbU7oUK/Zd9U8vCWsnpvww2KfQSm0qqydNp8w8YlQLMk+qxOan9KMLpzlQycz9Xr0yFcwenDT9Li8i+h6NDu1Fzd3W9bbOBxmi3r/p6l4+sb7IZiO1WrI5ru+ybhw2UxHc9Yr8ReGj4h1c1LOBIHEAJ00K/C7jUyyz+1Yr971fwzezkaC02Fc7IfWt1bZMiw+bnv3GodW5KJ/SOGxVRFgaTbjpDGqRnTAUJDhvc7Jdp6IfmAD3EGTNAtuk88upZrcm0XHfCCGq865nwcSWbXT7MZLjy7sTZxBiu4sEEXWF+8dfVoVHKdOYpWKjHvlqXr9QO4XrM0U+CzwhJBaE0V7REirRtT0z1Yv5twodQM8d6t+fIh2cPyvJkSzmba0kp+OwReSjTAlOMIokMJwB0ay92S/YbZPHRu0/3t8=
  - secure: Qi5BH9UfGNtl+znvO4DgrDmKUr4M/k3+hSPPZ6pGpVay8KDTzIAKEud4kNGjgXlbj8EsYzHp/eHaSp0vFwGmkdvlL/SPuxzWUpj6UHeNEqUOTo2MqJ4jZRfe+pyFmj4VQbC3mkf4WZ3fSxCrb3UZi5HGqpU4IZw4y1rejKfW2MbFBPNlxPjOJXBYSLIOLAMNw7VQFukRlz9GNEbgJoDSCUKuG2qUf7Lku8oMxKjMdUgxqji6zaMF4cs6WWDPD0zoLXS5yY7FVIHIS398o6RGqEUyzkZcS9GU+zPzAOEiFWmUeRVQFXUuFPQsR9CHlowGD+xCeDSMtGAm1HrQpa2jobWyCA3gmnSMzU+qzXBN5zWnL2S6Hf6U6igXMZ3Gq5dfA/fI1f3upCJv76rXvKLrO6JLa1eZ7MdTX7sujb8zANC7DMYC1Aq97eHNer15hYPtKJZUFvUNADBuWLaSGqoWvfNPuJ7xjjL/AToYuflSM8QqlhJ2EkziZI1xy9F6dQ+Bvr9tNF6MevzESdJun4JxKyqT9naIjWOtOycFWYMrrfDYvk4H5wzGywW0dUXiDSYMX9CqJWam6OC5wRwd9tquBhR6aN7JTpeJim6LCp3KaTbe8TGN4R1r0VS+bd5auW+v8LMrjVCbopYh5YL8cj3uNOIL6gn/JMUGmLxstOt/0H4=