language: java

sudo: false

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean test jacocoTestReport war"

after_success:
- bash <(curl -s https://codecov.io/bash)
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp build/libs/ROOT.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: Ir63AVnySdZx5T8MvAoJxqRULRm5BkS8KAaFccvM+o4ryhah6XKeHOmBNbnW483LbhzklYn3zNBHqeQRsvKE9H609C0F0/Fln7F3S2byAGTVvPLayyl4OPS6mNPw/GDXIogCRiZFDnSbpA3pJVfSbETm6yUWORT+cN1cKJ9WqY67SbbrpE+C1P3A/I3sE7sq3WmCB5HB0DAQ+Yg6CQD0sCOQ8RbtsLVWOlsl5Wkcv1mXDAAwdzuYMpu0eI/3ARtx2uL0P/S9DimDmg/qw5OAliETfPjhGhLexB0KMRpKge4cxOdE7VjJJhWHGu+VE8hK80hufWkvuRayrXyebYvnygaQQLcQ0OWsfmZ/NEAruXJ7Fu5x0aSRX4FKKvyhiCGklFMlp1cTKuHEMl7og2xg3MXtdntAnMKkBUXjlkAXExmJv5lvonGTXhhisbbugKaYvIZfPJS9+quHS0gkJKnmLW31WooX/Lqw/YAinwSizg9BmeOQAy7c2d33CqqxsXvz8XmI7wo4MsHiClQm7+Z3K092OzYKXoDTDJegmiR7wSy5uo2/RZi5VqwY5UpYpSyO+Vj7DW856cJAE4HiMFM+eWff+Fp3ZEpTJy8SxOdGOh+RCJoQNYnWHdaDZhIAzBDARb05OSz6zQ0i7phgiNr0MsRZLUCsfhneGwmmE0Lcsi4=
  - secure: n9KtuZoY2/t2IKfimogAFnSixAvbAROhsaS9yLuqJun8OIAhTPpHZbiBHWIPQTRwAXAUFaKama4OK7X2ulpysrIy9HBwXmMSJlG2rhUMVHX6OJyTaNFowzF8d3Uw/Asf2R2sq9n4znaMe+WNDW+l/S83JTEv5LQ8ANWkGX200Q+wg1BdN9fdYKWaOK8Co27v+T97h0B8qIJBSQTeI5bHMW6s60rAjeVrq12OFrsYyeX0+x6Gt2g2i9Hgj6VfoXVBW/Z9phGJct0O+mDsHlMeUQU+zND7qMICLwkXRbWt6oq/QVkNfW8a03Nm9a/3i5jkKMiU/MH70r+lxt8arLRhetP8Yfy3doZ/fo3qA51key48SnbSpVPy4zB/uy755Uc/xdRdYZ936aKkclAcqHvd/oYrtPuFCdpHLLar6YGgGTgs6AidoCj1WV+tXd5iFcni6fB2Hx5G2rdL4tUvOmgJmYhJmurfzK9uYnfRQu9CH/RKySBjQH3qoUA3upjug2HzhyO8+S3Tk81pmZPNXk6Edr7FulpSmIyUaTrlIZgok7aUfqRvQVTEUWMlwWQRmAOqUiOGUFi4tJT/fjq5HADJf9Sa+5FmrQ0HpmUYKB09C2Kt1abfGm3Xrnwe5/l66+eL/h0rvqd3nEFgbGEXf/z4uchaauxzaRronNaiGtEbQJU=
  - secure: rD5Ym3Gjt3/o3BQ5WQtp3EUSOqFlddo5PiBcvDtF81b3u1MfTkiR3VzdJmDqx4rAoOzNL1d8iqPl0/Ik0cI479h4VCcDHChP8SZF1rBrzSgLbaPFRPZrLuGi6LCOsRczOh8eBkPfJxBFRMCiHwjxx2osCol/FqYYrM1eOqYWMAe7iuQ0Y9C056GubqLQqDPRWEKk9cAUmoh5iLuKROOHDDpHO51TB7AmSjZxZH0f/paPHd+lhxRq/Z7/flwZYJVtZ0Wla+23+hlXhxt75XZoewG/PA17yYwVFNI/ww+9+y8tlrJMaQIR24iPT0tD1nt71LcHGCvm3E0rfXZUus82ouBF3CrwAkIgDJxq4Hq2YpJR+4J8fDelp5CDXsWW67vW4IAmmSIFMbjInTR/38/pume1LcPlz3uiDynx3+HAAkk1GwZkdCxhmnUapD4GRyuprOuavIojNG0QNXdsdUr3iB0Bgk6WMVaxL1SGamiEpgcg6Ipjc63P00VoBnj/3VQewdOdDBdP7XwOTFtRNvyysgO6g32ab3S7qfeoghFkBw+okRVGPh9h/rNax4uIHmP7P1N5voPhg44heiTvpImaMrbOoZH8SjAE47PhJi4E+xcAX7pm8NZpDvloGo65QH2VxqZJbBxSjL0OOczb1KaZ1PkieUhcKgvCF4MF8JqgIMo=