language: java

sudo: false

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean build jacocoTestReport"

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: openshift
  user: $OPENSHIFT_USER
  password:
    secure: $OPENSHIFT_PASSWORD
  app: kotlinmicroservice
  domain: $OPENSHIFT_DOMAIN
  on:
    repo: fcostaa/kotlin-microservice
    
cache:
  directories:
    - $HOME/.gradle
