language: java

sudo: required

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean test jacocoTestReport war"

after_success:
- bash <(curl -s https://codecov.io/bash)
- sudo apt-get -y install sshpass
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- sshpass scp -i ~/.ssh/id_rsa build/libs/ROOT.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: ANI+ignOfftZ38nGIOB0ZHT5auq0Nn4k+ty7O6MSKoPDQqqL9vp7Etdeg94X/4k+BLFLq6/leUC86DbHpdkYts/cabqK9QoTtjy/YA5tDgV8JQi/uKV81ET9HBKAhGA6JADEFn2Biz+AU8KiEOy9p3eyOUwznCPD1XkZCTdlex70WkXpMSjzxmGsVheuRZ/fGCBfcmECFAST/U1q5QFlhPI5EF0hcmMewNRSCYxCyN/kP7XtDKtMxKmxONq5o2JHtDX72thBvTiZwdMIhKazohrpR5pVMAAd61lOf4+2v7tr99WBuN4i2UGI20LYlKJWbmp2OneanLo4dPTMj5aMaOp+LqK8eGp2flXnw4QgsR80g93OC+uLipeDbhrYVefgTfltWKPBoSOtDtlrQ72zEmT0z6qxHVdrJTULHswKEbehG5IXNrHyxEIrAjOyzgjT5XriV2+Yn425/fKd9OTL9AsKUy5N2ehq3gJKAcjCTsvTkg4tluYYIKeSBNY4GkpZ/wyPFImwxqHuaaA79RUP4KfqvfjqVx87HarpNwqWLF/64rSJv8Sq1bpnjP5V2Oy9dhfz0pX4DC/8tN0MvvpghOeaOZOFqOBQTskNDmvn03SM4p/HVvjUgYbNboAffiqmYIdU0KlEKi7Ch6It51NMZPhuplNyukDGRbdecFa6FZI=
  - secure: VAYFCePuXOv2lA4ylinkRIKj6WJZBTJ3ZnI6+5mMpXln4ZYQBWm90OlzZhwffA/14AHms85N/ke5poakzOS3pC4ENTdGPcBiOUazKtpwpNQoWbUzx9YOG1nreM1n6FOhuQumByQHsxaOd2NOi9tB5ch0uU1McD2Q3374FTD7/WPu6oS+M78ac149vfxMS3FTTIyGNqtr5HamT/3IezJb5lh47scWwf6LvJUVdJ2l6aR6OBVZdzMM9OhXM3w4Z/o9pxpOXqk6BJyJHGx2tPuawzJEWkACel012i/bh/1CAtR2pGHQo9XgZzO+bazmRYzJSORdFgcvxNsF34PUf4Tt+6tp/KTpXKaudf9wNVLoJooT/9aCGbLQwTHfLT9E7ImzuI9Ka5E+EJ13KKZOwUVKJrbH5z7EeqQnkUuAdv6G7Nb2cvt95Riisi/deGclfF/QZaS/L9EtZNgLX2YHFxUb6ljPSFQhyVh6/y9VOuBreAOIxe2GhCKEogUVQaWrJCm7njnkyOypWaYWaDXNvhw+u/sDemy2NPXE7uvDLSv7HObf61KMpc6Kt2Qz3lc19QQLtC5zvvo6nhlvdbdUKWElk34PdrSp6GyO2sYL/xtlz6do7yXw4sVsSyzJ6o5qLUsX59oACzLyLfGhUScB3AY6CDE+sSORehuM8bhuiaKLNe4=
  - secure: NmrnWsgKPPbP3ipYONP2rTkHTPsnOeuSafTo+cQhkIkiXTVKkK96VlgnEj3z6Qf13VcjVX3WjADqEIBOmM9eGcSvPriEPvEsjFVdDiWohAR5RgLfyXBm1X34izaUHXuBVjx7vk2Ilj6MCtxHXnPS2OJGXBqV4zFDOzJjINUeOe+6BJCdW3/RB70/6k1VEctuZcAE7vJ6yT3X/2f0rvde0ADS5vN3MaWtL/+XBD+HQDTvA2QcfE/eLxkT63qQ4dqvx846JR2Cqmpi0IwLUPXuoEML5oixjrcmr8m8abLKYMDAAtcAylB1qFOcaVgGR18fnTkJP1vc0INHJCvW0l1dPzJlBlDhp04m4veQosnexnhCw1DADvCjNNcgRlAf74oqLxRTZV1S71jWQ93ljZe/InlJU68I9GjAtJaLN/OF2+uSOWYs27LWo8N4U/ty0mT34vIcsQBHwJM+RQrTi1fQ+HKGeGpQcihyeopT1RR73ZbQ32keIaqTvc7A563nd048FD79yvei/VGCSLxzKkWNTMUXDM86MuVe66boWkErRb1KHr8Q0YNsNaBpdaxn+BeLevuugzhca+sBsLDR3r75O+H7HJbcGXtKU+TzONGfnE05KnKx4iP6hTAvbyWsjXy44NSc/2OMrkgqPCV3gG+e1Lfgci2Aq2sJhbPPIzrd2HU=
