language: java

sudo: required

install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean build jacocoTestReport"

after_success:
- bash <(curl -s https://codecov.io/bash)
- sudo apt-get -y install sshpass
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- sshpass scp -i ~/.ssh/id_rsa build/libs/spark-*.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

before_install:
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - secure: njfaDRaZKmK2gFz/Yu9KGNI+2ByvFpR1AudjAHATpptKA83qjZq/GFaJrXbWE0kHVncqUeQOefQdI+Dc3njV4dcPtBhrfsxNt8Y2Gmv3EnRU9sB6ICtahdP93sFkOa/fheRv6vPHu78AnXsDS8ZfT73XKsoCvmcaU4B2UNowqB0BlxvVYcJ2CbuAYUX3BIkp/NuTpKI3N4MRbp4IAPBKRn0iCnczqpoDz+iWquvTjJCLTVs7RkwZxUbJZhS8ilP28VErIZDaeSKITmxJO83BAXJKvCf+hICbM9E6hjVXVX3SNVEMGYR1tzMQtw+H+XyBvgh3o+CVwN0ncpYSwqu3AbT88vOhePTdSGMC5iMaxXpQA2L9P/TlVPyldMqN7Hu8qOVpTWmCdF0r57gIJG440J+OEYXHUHLC9y4H7oRaVcdvDBD8WrjJYcvs1+lj8tU3hdAXDsPT74uOi5paLyXsoEemyxSjziN+sR/SeuOezeYTJJXyUax24+vogi6OdPVKWbzJ+eLSaI7NVcB9qlbjM/LIWKhOM0Yu+amcaoMbdY3ka+AYOuQvozaU9kK9s+1QSuxTySz3oXcAYkPin9cv0ZolyLidojUYJNZh1BJ3aOpyg/PaK4yk4kDjPZlXUC2dxUVKLXxyhkap7IhnVFehw9MzQ3RIVeyqN9dt++boWJs=
  - secure: oTSLw8U5PBbBOjkTZGHKfPrpzWHzKKJV7FTqim4mjnUO+4TwIzv3CAK/w8JP8SkGwCWa8Oggc9qRHd9uzWYsF9THEIszCUzwGRAvBfiBzltu+K6jSipBYH/wVHpNL/q6U4eiFQTTD+ebAPVHAQ48XHAi9DhcyXXXKrUU9g/awnds949L1/jZClnIsmi4eEX9OZM7B/D7d0Ni/BynrC+1itu0TXdwNheWlqxeHD96Vu0USz+zUz4evpRGNEavJ5rrJDpldG163lIurea4BHh1wAYWeeal2Af8qj+Xt2Y+pV50n6bpmM0cqJeGk0st9e9NBRMbRfMaV/EyfwlUgmvBcdFbJIoq3Wykf/0Kx0l0XwA8dwhwq5gjOGvYJe2yHBD6fJzvQSzxfvlrBH5ioMKAkgf35kcFRW44q8teEkR2yXelObNBi9HkgdJTPKnTwy4V6TL8zi2IRDbCaC+rvyI7IZ5IefTRfjhWZvbanDKHgbF/sHcQchb1IraotOsaj6rvpAN8Dz0pxwqHAjcTI+GLEjoU4OzuSrz9nVx5jRe6xtg4zpGcDiMFJPEJpLPWux0wqX1KwmcDFUbMfVI3MPxkFaE/QigVlwKTgMIMBKCIaS6BQjxn/NN6dDh8HG+ucc9W6ru7VnALb0QUGtSRCA20NZwifuoOGRxD7RxG+TbO4I0=
  - secure: ro0uIJcRfO8XWh4JFWAlK4u+z4uZSJsBPKKYEHH+EG7mMzGphOMBI1KMlIHG0Q4IuLGaRo8fr/aBtzvyjyllLs0/ASEpNMEH40eoQQ9tfPlHPWMkNEzbl8vKTC8w9pEmqZByptEpT/FtALVh0AuK2nN4s8Kw1O2JBdGHb4KB+LHOa8XzVsSYJkWOecdYJzXnWpBaNWmIlCbkoC6WU7Hj+xbdiCeLvhPLjbHozL7cGSDL0oqukAGcfSx2GPD1tl0VZFG8OTeZm1/oAHSdxmsDhmTjx0nyOjWX7isNOBl/2yhbyUcLoClIy2buZc9UfvYnee6xyDPM+ThWgolj3WC/ZEudgbG91cRSlK/laA/FZ28ceGAdPjRVRvHjSSh3VNX2tDDBX/OzODZq+9tgPqMcUDqIZLhEd87oAyXPv/zX9hJp5cSMszxV6mlW9XBTOk6AOJbN0pK7gz2X7SMkbQXhQZyhwTBS6IJeH6P9KkV2XF2pLJWgwpS27l868GPf+lkWhuXrnOFYg5iUDT7b/kwy7XlGr3ii8/diNsetwUQBFN0YUaVCy4rCJdgduYaDxhn/sGM7qze8FWWcAhxsdfhuxh8IeBYBDOXkmd7L7NYZKbbwsk41ona4lq3uDa2puG/HlzJe5WV+G4X3DBu4uxFeCkm5nwJclMTOprqvZo43q34=

deploy:
  provider: openshift
  user: felipe.h.j.costa@gmail.com
  password:
    secure: mOlniC+ewzpH9SG3eLXP6NvXskRjGOTQnyQ8WE9YFvBABHlIx0YhGMwyrEJpcnagZTannW7c+VxG51fHxnrg/O5dlJjZfd+Fu2R14TZ8kmgT3cdCfwMFi5zborL5NFz1RYpN9s/oQEXZlB11873TzN0+ijgJrZjwy3lEr+3rAeQGzgTe+oy0SYWhLGraIVDiQOSxkokCxmZDCWdkTripzlAwJjg4La3vf0h9zZq/II1mC+wPS8Yir21nMc/e3FwLwYRyZby9DOzEIWwBmwHbyZDg0kncevzvd+MYDYu1JcXx35Y6BAX1WGwJTN89OHqwWPArbPOTSHHOhfgZFjqj7Soyf4JJdV7dadUK7QGKQSnuAyrlyxoA2yn4OcXzGB/1RiOpQWMU8HEUYn8AMMI9eLTCWWL3tzE3zCV+3PgdZZRlQkOysS1vsjvqfsOgFLxfogGwnUQI3eNYLcLiTq09vo4tjYIiYGZinqAXgZm80Tqd/C6kPkes8ZN91CjQ2U5Mfvu87m0W7hdavAgxvtQMW6SzVKTvkFbGLxhsh7mVZYWFvnQj4vuuu/HL+yK+bQZA/iZMTy8Oa2+msxXaXJqmAUZHHA1VlohxIagLWW2zTzBL+7mdTtjLnNtc8uc2GBxRXR9Jr/329STm+o9EYtnmNDVaZjDfCGB6A24i6CfcSpc=
  app: kotlin-microservice
  domain: fcosta
  on:
    repo: fcostaa/kotlin-microservice
