language: java

sudo: false

addons:
  ssh_known_hosts:
  - kotlinmicroservice-fcosta.rhcloud.com
  apt:
    packages:
    - sshpass


install: true

jdk:
- oraclejdk8

script:
- "./gradlew clean test jacocoTestReport jar"

after_success:
- bash <(curl -s https://codecov.io/bash)
- openssl aes-256-cbc -K $encrypted_b4f0cf043b2b_key -iv $encrypted_b4f0cf043b2b_iv
  -in id_rsa.enc -out ~/id_rsa_dpl -d
- chmod 600 ~/id_rsa_dpl
- eval "$(ssh-agent)"
- ssh-add
- export SSHPASS=$DEPLOY_PASS
- scp -i ~/id_rsa_dpl build/libs/app-0.1.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

cache:
  directories:
  - "$HOME/.gradle"

deploy:
  skip_cleanup: true
  provider: openshift
  user: felipe.h.j.costa@gmail.com
  password:
    secure: MjrG7tVLA38+1O0UCwXOStQ29mU8AZao3ARw+a0gLd3JCjJZ1cekazpPB0UPTTciR2KJoD2OL/KUxgijRXaq88+2BYhOAC9rMscudRhlLBeJpAW/F9EMD6ug/O9WuB3u3pvXWE+RVyNCvA8OlSH5IV/JelsqtOw2bBtKUS4D714TsCQVG58DKYbWtTWrgbNgZouUls5I9KRC4Kbu6lAhzN+FuKqB/Fd+n1npMhWGxTmxvlPRXOJ/P031erugF695kJqKJqaS1MxkLzOMeN23puYWyg8KzgPUu7QbTG/B6UQbd50tyqr7jeuZz/Jkuoj7rt+AN2iHG1pdCT/mSBFs+xUA+cRvhIbIMX1DBvVpK1FdAQC9x97LSyDlns148okJ07KzYtEx9nNC60siOaXoPXbNxJ+z5xVJU3N7mqFwjIfoF4o+K0dHN7d7NFsm/VqGEjsGe+TWxBtR7Ngc5htYeeQyaEOBMDf1h2x+QVz0g8poXGnboMa+Bg8J1Ux4dNsk6yXPgsobNYWGPI7gK4ms7har0t4I63h0vO05lguQVRt62LW730VLdotLmbdQ+W5jwuMCHtY+Zcugt1mDY0KihmdbNRzuoMEPxgobQncicpVkEqJaumFFTUQ417VuAQf3j+Z5lK8ZD7BTATb6ciIpceWEzBIx6YgPxvPgBhn6Ol8=
  app: kotlinmicroservice
  domain: fcosta
  on:
    repo: fcostaa/kotlin-microservice

env:
  global:
  - secure: UGHsmp4d93JVKXwweJkszNmbrW40uIsCQp87atvFttW83jA43JWMBz9cDa/uzHd+Uzy7KSXHe3CaknBWJ8ttNm02GzZWjzIbR3rfAifPcf7cR8faddsR0AkVmVQnHj+QG8Yfb6yCR3TT4b3HVVwJc5oU8p65k3ixBkdZAmvqWa7GKjjKqh8aXQP4wOVe53sHf/Pxen68yjgPzaXjf0pLcfDcXvy7r027sWynyRic95BHPVjTlyMI2OOZ6kvnspTHJhNcjz5UGE1H3j7cclvUTez4ZYAEtg4nOFWVvjsaDZgQ1tMcqsTtmLz9D07ov4gmWXpluRVfwCuwaWf5oaoPQ3QLTO0uM4nM/vzErrnlCQ40LD/JEsAm36h4DYTcFKRPQRp8sdNWmwV++y8U6CQH/WIchnSHPAGdr17tz+R9UESWZAOsPClHCyu8EDudK/Mir+TjYRdRMAmhTltjsIBZWiCNj9MwX8sMrfSpRNdjUCJDkL/BuZl7AWycCtB8Bb+RiF9ukucHf04P9tl82aQeLhfdngKYJP/7Ln2sPsL+jFQ7PBIAa0pmWiflvFsOKBczeJANif4NgEjeYlUuCDOXlQYVhMcmG4EqlSKXRRQ4qTAHb34I86SccxBI0p6VcPHK+491+2o9QwJdwmlqDltEv/E1KhUfRgYWqobu4BndMgQ=
  - secure: g3AwPyEe6rA0Vqc6D31dR0r0rikknxSmQ0wPyFJFLmzhTjmaUvrtEyAifD7cXWyDryFTi6WqTfNCsLdJ0EzyH0g4bUwcrwKNUp94CQBn4poiUv/HpLVymlDBeOh5FrAf2jdnYcgYnUPHRMKvELEIl1bFg7tBoKbBPy0lv9IHz9DL2m9BDsWZ5w8JrwFvAJx9sp0UCsRi6eOKuFyvQyvfhTUcV8BXyS+2M/nso0jOrpjfI/ZZe/33AEEYOSIyrT3kyf20zhEK1w3IFKgXRLSDqTonJ0CKQCBR29cDSS+8kfz7PLcuJuEUpT5l+UGSsjr/aPZGX9hi0aSMWjCWDsgmHG3zbcVjiyYX2Ao8/m2RI5yX8o6zJ1Gl5pi2miKy0gA5fRiMeQ/PauhK/L6TWMS59tv6hsWoFSI06fEIVuuffUA/x9xaQ4RHOrJhXLkLBXtSK7YgBjpKwEhiDJ/hOxDvN9sy2tMr7Un0hGRT5eZ4a6dPCu6FwOiNHP49L05NmlqJZoOZDI7j+9G5+5SkjSJ4MtJvCsqVXggEUefmlkCsz4EpIQIZh0xm0uXwW0JL+j+7cZSKHTXaFtNnsGYPL2iJAs0AZlim57yB9c6RwezyYDbJB0RZ4W1x7Bb9Yt6VBBQEDaQAww6qpAOvxHvzPDY9fnjyihWMdMyyI868UUgGz2U=
  - secure: Q9na0DJXjbOLdaR4KnIjUei7g4bndjbjyjD8w0x5oPmjKHc6qI42M0SyIyt60efONWfKf2ZPKf0XWjdDMq5Qp/BdLJUGK+Skx1J+Tg9H0pmTabxycDJFIraLYkp1wMLQW3LECp34BL52E7kOxC97H9c9tLOaCjgv8oNazEioU8i9a6sRG0dCvwEWwP8DeWCr2VvHeXLdrxT4Q/98UaL09M8pSjvfNM65Z9CJ/UIdvvDEhIwtbHpK5La3DLEW0cL/7q92emia0HJk3rErSsRuG5V4xaT0hbxxtv3vNuGDSo6XPKr8I7hDR9gtxQMHL/6C7thMw1nb5ycKRZMM5YPgddyFpy1w0AkmuBzz6DvlKDpZwCpNuRuqHVNC2BY4Xrsw5ZNNdQldA5KPGdTyJr/bsn/+XImD4FGFxwaLNZc9yBliwyV9ZwTspEcICs8YzogTkklhrxJAyM6Ywgaf5wDhtsbwfip0i7Mm1XoaeaHa5mz+SwoO1gZ2ZnOX1qNeg7FAMPdZ39COiHG/EeKLL/K2bx0taabAj63sAmy9Ci05tu4tM0BGuVvi1hbeMHU2DX5JASF7gFYsjgO01n9D2u6rtnIS/zv96jciaSnLJqXS5IW/woBB+zitdM73zCOfabQyg1akI8QQpkpvHQz041rugI5P5Ku93VlfS7v1jFjyXX0=
