version: '3'
services:
  app:
    build: docker/development
    environment:
      PORT: '8080'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - redis
    ports:
      - "8080:8080"
      - "50505:50505"

  redis:
    image: redis:3.2.9
    ports:
      - "6379:6379"